/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */
package userinterface.scientistWorkArea;

import business.Ecosystem;
import business.drug.Compound;
import business.drug.Drug;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.organization.ScientistOrganization;
import business.scientist.Scientist;
import business.userAcoount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harsh
 */
public class CreateDrugJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    Ecosystem business;
    ArrayList<Compound> tempList;
    private UserAccount account;
    private Organization organization;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public CreateDrugJPanel(JPanel userProcessContainer, Enterprise enterprise, Ecosystem business, ArrayList<Compound> tempList, UserAccount account, Organization org) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.business = business;
        this.tempList = tempList;
        this.account = account;
        this.organization = org;
        populateCompoundTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateCompoundTable() {
        DefaultTableModel model = (DefaultTableModel) compoundJTable.getModel();
        model.setRowCount(0);

        for (Compound c : tempList) {
            Object row[] = new Object[3];
            row[0] = c;
            row[1] = c.getMolecularWeight();
            row[2] = c.getQuantity();
            model.addRow(row);
        }

    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        drugIdJTextField = new javax.swing.JTextField();
        drugNameJTextField = new javax.swing.JTextField();
        usesJTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionJTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        compoundJTable = new javax.swing.JTable();
        backJbtn = new javax.swing.JButton();
        createJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Levenim MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("                 Create Drug");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 370, -1));

        jLabel2.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Drug Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Uses:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 60, -1));

        jLabel4.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Drug ID:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 60, -1));
        add(drugIdJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 270, -1));
        add(drugNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 270, -1));
        add(usesJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 270, -1));

        descriptionJTextArea.setColumns(20);
        descriptionJTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionJTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 420, 60));

        jLabel5.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Description:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        compoundJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Molecular Weight", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(compoundJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 490, 80));

        backJbtn.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        backJbtn.setText("Back");
        backJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbtnActionPerformed(evt);
            }
        });
        add(backJbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 70, -1));

        createJBtn.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        createJBtn.setText("Create");
        createJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJBtnActionPerformed(evt);
            }
        });
        add(createJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJBtnActionPerformed
        // TODO add your handling code here:
        String drugName = drugNameJTextField.getText();
        String drugDesciprtion = descriptionJTextArea.getText();
        String drugUses = usesJTextField.getText();

        if (drugName.equals("") || drugDesciprtion.equals("") || drugUses.equals("")) {
            JOptionPane.showMessageDialog(this, "Please provide the Drug name,description and its uses!!");
            return;
        } else if (organization instanceof ScientistOrganization) {
            for (Scientist s : organization.getScientistDirectory().getScientistDirectory()) {
                if (account.getEmployee().getName().equals(s.getName())) {
                    Drug d = s.addDrugInList();
                    d.setDrugName(drugNameJTextField.getText());
                    d.setDescription(descriptionJTextArea.getText());
                    d.setUses(usesJTextField.getText());
                    d.setCopoundComposition(tempList);
                    d.setClinicalTrialStatus("Pending");
                    JOptionPane.showMessageDialog(this, "Drug Created Successfully!!");
                }
            }
        }

    }//GEN-LAST:event_createJBtnActionPerformed

    private void backJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        if (component instanceof ScientistWorkAreaJPanel) {
            ScientistWorkAreaJPanel s = (ScientistWorkAreaJPanel) component;
            s.populateDrugTable();
        }
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJbtn;
    private javax.swing.JTable compoundJTable;
    private javax.swing.JButton createJBtn;
    private javax.swing.JTextArea descriptionJTextArea;
    private javax.swing.JTextField drugIdJTextField;
    private javax.swing.JTextField drugNameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField usesJTextField;
    // End of variables declaration//GEN-END:variables

}
