/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package userinterface.scientistWorkArea;


import business.Ecosystem;
import business.drug.Drug;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.organization.ScientistOrganization;
import business.scientist.Scientist;
import business.userAcoount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Harsh
 */
public class ViewDrugJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    Ecosystem business;
    UserAccount account;
    Organization org;
    
    /** Creates new form AdminWorkAreaJPanel */
    public ViewDrugJPanel(JPanel userProcessContainer, Enterprise enterprise,Ecosystem business,UserAccount account,Organization org) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.business = business;
        this.account=account;
        this.org = org;
        populateDrugTable();
      
    }
    
    
   public void  populateDrugTable(){
        
        DefaultTableModel model = (DefaultTableModel) DrugjTable.getModel();
        model.setRowCount(0);
        
        for(Organization o:enterprise.getOrganizationDirectory().getOrganizationList()){
            if(o instanceof ScientistOrganization){
                 for(Scientist s:o.getScientistDirectory().getScientistDirectory()){
                     if(account.getEmployee().getName().equals(s.getName())){
                         for(Drug d:s.getDrugList()){
                              Object row[] = new Object[2];
            row[0] = d.getDrugNumber();
            row[1] = d;
            
            
            model.addRow(row);
                         }
                     }
                 }
        } 
        }
       
        
        
        
    }
    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJlbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DrugjTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerJlbl.setFont(new java.awt.Font("Levenim MT", 1, 24)); // NOI18N
        headerJlbl.setForeground(new java.awt.Color(0, 204, 204));
        headerJlbl.setText("View Created Drugs");
        add(headerJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 250, 40));

        DrugjTable.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        DrugjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DrugName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DrugjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 530, 130));

        backJButton.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DrugjTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel headerJlbl;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
