/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */
package userinterface.administrativeRole;

import business.enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author bharat
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueJLabel.setText(enterprise.getName());
        System.out.println("Enterprise "+enterprise.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myWorkAreaAdminRoleJLabel = new javax.swing.JLabel();
        manageUserJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        enterpriseJLabel = new javax.swing.JLabel();
        valueJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myWorkAreaAdminRoleJLabel.setFont(new java.awt.Font("Levenim MT", 1, 24)); // NOI18N
        myWorkAreaAdminRoleJLabel.setForeground(new java.awt.Color(0, 204, 204));
        myWorkAreaAdminRoleJLabel.setText("Administrator Work Area");
        myWorkAreaAdminRoleJLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(myWorkAreaAdminRoleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        manageUserJButton.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        manageUserJButton.setText("Manage User");
        manageUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserJButtonActionPerformed(evt);
            }
        });
        add(manageUserJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 190, -1));

        manageEmployeeJButton.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        manageEmployeeJButton.setText("Manage Employee");
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 190, -1));

        manageOrganizationJButton.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        manageOrganizationJButton.setText("Manage Organization");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 190, -1));

        enterpriseJLabel.setFont(new java.awt.Font("Levenim MT", 1, 20)); // NOI18N
        enterpriseJLabel.setForeground(new java.awt.Color(0, 204, 204));
        enterpriseJLabel.setText("ENTERPRISE:");
        enterpriseJLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(enterpriseJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 140, 30));

        valueJLabel.setFont(new java.awt.Font("Levenim MT", 1, 11)); // NOI18N
        valueJLabel.setForeground(new java.awt.Color(0, 204, 204));
        valueJLabel.setText("<value>");
        add(valueJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUserJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseJLabel;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton manageUserJButton;
    private javax.swing.JLabel myWorkAreaAdminRoleJLabel;
    private javax.swing.JLabel valueJLabel;
    // End of variables declaration//GEN-END:variables

}
