/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */
package userinterface.supplierWorkArea;

import business.drug.Compound;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.supplier.Supplier;
import business.userAcoount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import business.organization.SupplierOrganization;

/**
 *
 * @author bharat
 */
public class AddCompoundJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount account;
    private Organization organization;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AddCompoundJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.organization = organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJlbl = new javax.swing.JLabel();
        nameJlbl = new javax.swing.JLabel();
        molecularWeightJlbl = new javax.swing.JLabel();
        costJlbl = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        molecularWeightJTextField = new javax.swing.JTextField();
        quantityJTextField = new javax.swing.JTextField();
        addCompoundJButton = new javax.swing.JButton();
        backJBtn = new javax.swing.JButton();
        quantityJlbl = new javax.swing.JLabel();
        costJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerJlbl.setFont(new java.awt.Font("Levenim MT", 1, 24)); // NOI18N
        headerJlbl.setForeground(new java.awt.Color(0, 204, 204));
        headerJlbl.setText("                Add Compound");
        add(headerJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 410, -1));

        nameJlbl.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        nameJlbl.setForeground(new java.awt.Color(0, 204, 204));
        nameJlbl.setText("Name                :");
        add(nameJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 120, -1));

        molecularWeightJlbl.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        molecularWeightJlbl.setForeground(new java.awt.Color(0, 204, 204));
        molecularWeightJlbl.setText("Molecular weight:");
        add(molecularWeightJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        costJlbl.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        costJlbl.setForeground(new java.awt.Color(0, 204, 204));
        costJlbl.setText("Cost                   :");
        add(costJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 200, -1));
        add(molecularWeightJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 200, -1));
        add(quantityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 200, -1));

        addCompoundJButton.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        addCompoundJButton.setText("Add Compound");
        addCompoundJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCompoundJButtonActionPerformed(evt);
            }
        });
        add(addCompoundJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        backJBtn.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        backJBtn.setText("<<Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });
        add(backJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 320, 110, -1));

        quantityJlbl.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        quantityJlbl.setForeground(new java.awt.Color(0, 204, 204));
        quantityJlbl.setText("Quantity          :   ");
        add(quantityJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 90, -1));
        add(costJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addCompoundJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCompoundJButtonActionPerformed
        // TODO add your handling code here:
        String regexp = "(?<=^| )\\d+(\\.\\d+)?(?=$| )|(?<=^| )\\.\\d+(?=$| )\n";
        String name = nameJTextField.getText();
        String molecularWeight = molecularWeightJTextField.getText();
        String cost = costJTextField.getText();
        String quantity = quantityJTextField.getText();
        if (name.equals("") || molecularWeight.equals("") || cost.equals("") || quantity.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter all the details!!");
            return;
        } else if (!cost.matches(regexp)) {
            JOptionPane.showMessageDialog(this, "Invalid Cost! Please enter valid details!!");
            return;
        } else if (!quantity.matches(regexp)) {
            JOptionPane.showMessageDialog(this, "Invalid Quantity! Please enter valid details!!");
            return;
        } else if (!molecularWeight.matches(regexp)) {
            JOptionPane.showMessageDialog(this, "Invalid molecularWeight! Please enter valid details!!");
            return;
        } else {
            for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (o instanceof SupplierOrganization) {
                    for (Supplier s : o.getSupplierDirectory().getSuppliersList()) {
                        if (account.getEmployee().getName().equals(s.getName())) {
                            Compound c = s.getCompoundHistory().addCompund();
                            c.setName(nameJTextField.getText());
                            c.setMolecularWeight(Float.parseFloat(molecularWeightJTextField.getText()));
                            c.setCost(Double.parseDouble(costJTextField.getText()));
                            c.setQuantity(Double.parseDouble(quantityJTextField.getText()));
                            JOptionPane.showMessageDialog(null, "Compound added successfully");
                            nameJTextField.setText("");
                            molecularWeightJTextField.setText("");
                            costJTextField.setText("");
                            quantityJTextField.setText("");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_addCompoundJButtonActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCompoundJButton;
    private javax.swing.JButton backJBtn;
    private javax.swing.JTextField costJTextField;
    private javax.swing.JLabel costJlbl;
    private javax.swing.JLabel headerJlbl;
    private javax.swing.JTextField molecularWeightJTextField;
    private javax.swing.JLabel molecularWeightJlbl;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel nameJlbl;
    private javax.swing.JTextField quantityJTextField;
    private javax.swing.JLabel quantityJlbl;
    // End of variables declaration//GEN-END:variables

}
