/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */
package userinterface.supplierWorkArea;

;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.userAcoount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author bharat
 */


public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount account;
    Organization organization;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public SupplierWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.organization = organization;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJlbl = new javax.swing.JLabel();
        addCompoundJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        viewCompoundsJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerJlbl.setFont(new java.awt.Font("Levenim MT", 1, 24)); // NOI18N
        headerJlbl.setForeground(new java.awt.Color(0, 204, 204));
        headerJlbl.setText("Supplier Work Area");
        add(headerJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 270, -1));

        addCompoundJButton.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        addCompoundJButton.setText("Add compound");
        addCompoundJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCompoundJButtonActionPerformed(evt);
            }
        });
        add(addCompoundJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 190, -1));

        enterpriseLabel.setFont(new java.awt.Font("Levenim MT", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(0, 204, 204));
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        valueLabel.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(0, 204, 204));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));

        viewCompoundsJBtn.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        viewCompoundsJBtn.setText("View Compounds");
        viewCompoundsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCompoundsJBtnActionPerformed(evt);
            }
        });
        add(viewCompoundsJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addCompoundJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCompoundJButtonActionPerformed

        AddCompoundJPanel addCompoundJPanel = new AddCompoundJPanel(userProcessContainer, account, enterprise, organization);
        userProcessContainer.add("addCompoundJPanel", addCompoundJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addCompoundJButtonActionPerformed

    private void viewCompoundsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCompoundsJBtnActionPerformed
        // TODO add your handling code here:

        ViewCompoundListJPanel vcljp = new ViewCompoundListJPanel(userProcessContainer, account, enterprise, organization);
        userProcessContainer.add("ViewCompoundListJPanel", vcljp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_viewCompoundsJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCompoundJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel headerJlbl;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton viewCompoundsJBtn;
    // End of variables declaration//GEN-END:variables

}
