/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.patientWorkArea;

import business.Ecosystem;
import business.enterprise.Enterprise;
import business.organization.DoctorOrganization;
import business.organization.Organization;
import business.userAcoount.UserAccount;
import java.awt.CardLayout;
import business.organization.PatientOrganization;
import business.workqueue.ScheduleAppointmentWorkRequest;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bharat
 */
public class ScheduleAppointmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Ecosystem business;
    private UserAccount userAccount;
    private PatientOrganization patientOrganization;
    private Enterprise enterprise;

    public ScheduleAppointmentJPanel(JPanel userProcessContainer, Ecosystem business, UserAccount userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.patientOrganization = (PatientOrganization) organization;
        this.enterprise = enterprise;
        patientNameJlbl.setText(userAccount.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        purposeJTxt = new javax.swing.JTextArea();
        submitOfScheduleApmtJButton = new javax.swing.JButton();
        backOfScheduleApmtJButton = new javax.swing.JButton();
        patientNameJlbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateJDateChooser = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Levenim MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Schedule an Appointment");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 19, -1, -1));

        jLabel5.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Name                          :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 129, 150, -1));

        jLabel6.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Purpose of Visit            :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 204, 147, -1));

        purposeJTxt.setColumns(20);
        purposeJTxt.setRows(5);
        jScrollPane1.setViewportView(purposeJTxt);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 204, 220, -1));

        submitOfScheduleApmtJButton.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        submitOfScheduleApmtJButton.setText("Submit");
        submitOfScheduleApmtJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitOfScheduleApmtJButtonActionPerformed(evt);
            }
        });
        add(submitOfScheduleApmtJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 354, 109, -1));

        backOfScheduleApmtJButton.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        backOfScheduleApmtJButton.setText("<<Back");
        backOfScheduleApmtJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backOfScheduleApmtJButtonActionPerformed(evt);
            }
        });
        add(backOfScheduleApmtJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 354, 104, -1));

        patientNameJlbl.setText("jLabel2");
        add(patientNameJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Select Date                 :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 150, -1));

        dateJDateChooser.setMinSelectableDate(new Date());
        add(dateJDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitOfScheduleApmtJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitOfScheduleApmtJButtonActionPerformed
        // TODO add your handling code here:

        String purpose = purposeJTxt.getText();
        Date appointmentDate = dateJDateChooser.getDate();
        if (purpose.equals("")) {
            JOptionPane.showMessageDialog(this, "Please provide your purpose of visit!!");
            return;
        } else if (appointmentDate== null) {
            JOptionPane.showMessageDialog(this, "Please provide your appointment date!!");
            return;
        } else {
            ScheduleAppointmentWorkRequest request = new ScheduleAppointmentWorkRequest();
            request.setMessage(purpose);
            request.setSender(userAccount);
            request.setStatus("New Appointment");
            request.setAppointmentResolution("Yet to be prescribed");
            request.setRequestDate(new Date());
            request.setAppointmentDate(appointmentDate);
            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof DoctorOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(this, "Appointment scheduled successfully!!");
                purposeJTxt.setText("");
            }
        }

    }//GEN-LAST:event_submitOfScheduleApmtJButtonActionPerformed

    private void backOfScheduleApmtJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backOfScheduleApmtJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PatientWorkAreaJPanel pwajp = (PatientWorkAreaJPanel) component;
        pwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backOfScheduleApmtJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backOfScheduleApmtJButton;
    private com.toedter.calendar.JDateChooser dateJDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel patientNameJlbl;
    private javax.swing.JTextArea purposeJTxt;
    private javax.swing.JButton submitOfScheduleApmtJButton;
    // End of variables declaration//GEN-END:variables
}
