/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.doctorWorkArea;

import business.Ecosystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.userAcoount.UserAccount;
import javax.swing.JPanel;
import business.organization.DoctorOrganization;
import business.organization.Organization;
import java.awt.CardLayout;

/**
 *
 * @author Ujjval
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Ecosystem business;
    private UserAccount userAccount;
    private DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    private Network inNetwork;

    public DoctorWorkAreaJPanel(JPanel userProcessContainer, Ecosystem business, UserAccount userAccount, Organization organization, Enterprise enterprise,Network inNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.doctorOrganization = (DoctorOrganization) organization;
        this.enterprise = enterprise;
        this.inNetwork=inNetwork;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJLabel = new javax.swing.JLabel();
        treatPatientsJBtn = new javax.swing.JButton();
        requestStudyJbtn = new javax.swing.JButton();
        showReportsJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerJLabel.setFont(new java.awt.Font("Levenim MT", 1, 24)); // NOI18N
        headerJLabel.setForeground(new java.awt.Color(0, 204, 204));
        headerJLabel.setText("Doctor Work Area");
        add(headerJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 26, 255, -1));

        treatPatientsJBtn.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        treatPatientsJBtn.setText("Treat Patients");
        treatPatientsJBtn.setBorder(null);
        treatPatientsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatPatientsJBtnActionPerformed(evt);
            }
        });
        add(treatPatientsJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 117, 140, 38));

        requestStudyJbtn.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        requestStudyJbtn.setText("Request Study");
        requestStudyJbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        requestStudyJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestStudyJbtnActionPerformed(evt);
            }
        });
        add(requestStudyJbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 185, 140, 37));

        showReportsJButton.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        showReportsJButton.setText("Show Reports");
        showReportsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showReportsJButtonActionPerformed(evt);
            }
        });
        add(showReportsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 253, 140, 37));
    }// </editor-fold>//GEN-END:initComponents

    private void treatPatientsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatPatientsJBtnActionPerformed
        // TODO add your handling code here:
        TreatPatientsJPanel TreatPatientsJPanel = new TreatPatientsJPanel(userProcessContainer, business, userAccount, doctorOrganization);
        userProcessContainer.add("TreatPatientsJPanel", TreatPatientsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_treatPatientsJBtnActionPerformed

    private void requestStudyJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestStudyJbtnActionPerformed
        // TODO add your handling code here:
        RequestStudyJPanel rsjp = new RequestStudyJPanel(userProcessContainer, business, userAccount, doctorOrganization, enterprise,inNetwork);
        userProcessContainer.add("RequestStudyJPanel", rsjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestStudyJbtnActionPerformed

    private void showReportsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showReportsJButtonActionPerformed
        // TODO add your handling code here:

        ShowReportsJPanel srjp = new ShowReportsJPanel(userProcessContainer, business, userAccount, doctorOrganization, enterprise);
        userProcessContainer.add("ShowReportsJPanel", srjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_showReportsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headerJLabel;
    private javax.swing.JButton requestStudyJbtn;
    private javax.swing.JButton showReportsJButton;
    private javax.swing.JButton treatPatientsJBtn;
    // End of variables declaration//GEN-END:variables
}
