/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.doctorWorkArea;

import business.workqueue.ScheduleAppointmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ujjval
 */
public class PatientTreatedJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientTreatedJPanel
     */
    JPanel userProcessContainer;
    ScheduleAppointmentWorkRequest request;

    public PatientTreatedJPanel(JPanel userProcessContainer, ScheduleAppointmentWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJlbl = new javax.swing.JLabel();
        submitJbtn = new javax.swing.JButton();
        backJBtn = new javax.swing.JButton();
        resolutionPrescribedJlbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resolutionPrescribedJtxtArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerJlbl.setFont(new java.awt.Font("Levenim MT", 1, 24)); // NOI18N
        headerJlbl.setForeground(new java.awt.Color(0, 204, 204));
        headerJlbl.setText("Patient Treatment Panel");
        add(headerJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 21, -1, -1));

        submitJbtn.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        submitJbtn.setText("Submit Prescription");
        submitJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJbtnActionPerformed(evt);
            }
        });
        add(submitJbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 355, -1, -1));

        backJBtn.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        backJBtn.setText("<<Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });
        add(backJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 355, -1, -1));

        resolutionPrescribedJlbl.setFont(new java.awt.Font("Levenim MT", 1, 18)); // NOI18N
        resolutionPrescribedJlbl.setForeground(new java.awt.Color(0, 204, 204));
        resolutionPrescribedJlbl.setText("Resolution Prescribed:");
        add(resolutionPrescribedJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 122, -1, -1));

        resolutionPrescribedJtxtArea.setColumns(20);
        resolutionPrescribedJtxtArea.setRows(5);
        jScrollPane1.setViewportView(resolutionPrescribedJtxtArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 122, 372, 172));
    }// </editor-fold>//GEN-END:initComponents

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        TreatPatientsJPanel tpjp = (TreatPatientsJPanel) component;
        tpjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed

    private void submitJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJbtnActionPerformed
        // TODO add your handling code here:
        String result = resolutionPrescribedJtxtArea.getText();
        if (result.equals("")) {
            JOptionPane.showMessageDialog(this, "Please provide a prescription!!");
        } else {
            request.setAppointmentResolution(result);
            request.setStatus("Treatment Complete");
            request.setResolveDate(new Date());
            JOptionPane.showMessageDialog(this, "Patient treated Successfully!!");
        }
    }//GEN-LAST:event_submitJbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JLabel headerJlbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel resolutionPrescribedJlbl;
    private javax.swing.JTextArea resolutionPrescribedJtxtArea;
    private javax.swing.JButton submitJbtn;
    // End of variables declaration//GEN-END:variables
}
