/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.doctorWorkArea;

import business.Ecosystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.DoctorOrganization;
import business.organization.Organization;
import business.organization.ScientistOrganization;
import business.userAcoount.UserAccount;
import business.workqueue.StudyWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ujjval
 */
public class RequestNewStudyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestNewStudyJPanel
     */
    private JPanel userProcessContainer;
    private Ecosystem business;
    private UserAccount userAccount;
    private DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    private Network inNetwork;

    public RequestNewStudyJPanel(JPanel userProcessContainer, Ecosystem business, UserAccount userAccount, Organization organization, Enterprise enterprise, Network inNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.doctorOrganization = (DoctorOrganization) organization;
        this.enterprise = enterprise;
        this.inNetwork = inNetwork;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        headerJLbl = new javax.swing.JLabel();
        studyNameJlbl = new javax.swing.JLabel();
        studyMessageJlbl = new javax.swing.JLabel();
        studyNameJTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        studyMessageJTxt = new javax.swing.JTextArea();
        backJBtn = new javax.swing.JButton();
        submitJBtn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(51, 51, 51));
        setFont(new java.awt.Font("Levenim MT", 1, 24)); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerJLbl.setFont(new java.awt.Font("Levenim MT", 1, 24)); // NOI18N
        headerJLbl.setForeground(new java.awt.Color(0, 204, 204));
        headerJLbl.setText("Request New Study");
        add(headerJLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 11, 265, -1));

        studyNameJlbl.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        studyNameJlbl.setForeground(new java.awt.Color(0, 204, 204));
        studyNameJlbl.setText("Study Name:");
        add(studyNameJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 74, -1, -1));

        studyMessageJlbl.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        studyMessageJlbl.setForeground(new java.awt.Color(0, 204, 204));
        studyMessageJlbl.setText("Study Message:");
        add(studyMessageJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 121, -1, -1));
        add(studyNameJTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 72, 278, -1));

        studyMessageJTxt.setColumns(20);
        studyMessageJTxt.setRows(5);
        jScrollPane1.setViewportView(studyMessageJTxt);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 121, 279, 149));

        backJBtn.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        backJBtn.setText("<<Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });
        add(backJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 307, -1, -1));

        submitJBtn.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        submitJBtn.setText("Submit");
        submitJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJBtnActionPerformed(evt);
            }
        });
        add(submitJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 307, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJBtnActionPerformed
        // TODO add your handling code here:

        String studyName = studyNameJTxt.getText();
        String studyMessage = studyMessageJTxt.getText();

        if (studyMessage.equals("") || studyName.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter both details!");
            return;
        } else {
            StudyWorkRequest request = new StudyWorkRequest();
            request.getStudy().setStudyName(studyName);
            request.setMessage(studyMessage);
            request.setSender(userAccount);
            request.setStatus("New Study");
            request.setDrug(null);
            request.setRequestDate(new Date());
            request.getStudy().setRecruitmentStatus("New");
            request.getStudy().setRecruitmentNumber(0);
            request.getStudy().setPhase("New Study");
            Organization org = null;

            for (Network n : business.getNetworkList()) {
                if (n.getName().equals(inNetwork.getName())) {
                    for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                        for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                            if (o instanceof ScientistOrganization) {
                                org = o;
                                break;
                            }
                        }
                    }
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);

            }
            JOptionPane.showMessageDialog(this, "Request Submitted Successfully!");
        }
    }//GEN-LAST:event_submitJBtnActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RequestStudyJPanel rnsjp = (RequestStudyJPanel) component;
        rnsjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JLabel headerJLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea studyMessageJTxt;
    private javax.swing.JLabel studyMessageJlbl;
    private javax.swing.JTextField studyNameJTxt;
    private javax.swing.JLabel studyNameJlbl;
    private javax.swing.JButton submitJBtn;
    // End of variables declaration//GEN-END:variables
}
