/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.doctorWorkArea;

import business.Ecosystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.DoctorOrganization;
import business.organization.Organization;
import business.organization.PatientOrganization;
import business.patient.Patient;
import business.userAcoount.UserAccount;
import business.workqueue.StudyWorkRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ujjval
 */
public class RequestStudyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestStudyJPanel
     */
    private JPanel userProcessContainer;
    private Ecosystem business;
    private UserAccount userAccount;
    private DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    private Network inNetwork;

    public RequestStudyJPanel(JPanel userProcessContainer, Ecosystem business, UserAccount userAccount, Organization organization, Enterprise enterprise,Network inNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.doctorOrganization = (DoctorOrganization) organization;
        this.enterprise = enterprise;
        this.inNetwork=inNetwork;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) studyRequestsJTable.getModel();
        model.setRowCount(0);
       
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
           
            Object[] row = new Object[6];
            row[0] = ((StudyWorkRequest) request).getStudy().getStudyName();
            row[1] = request;
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();
            String result = ((StudyWorkRequest) request).getDrug() == null ? "Yet to be Decided" : ((StudyWorkRequest) request).getDrug().getDrugName();
            row[4] = result;
            row[5] = ((StudyWorkRequest) request).getStudy().getRecruitmentStatus();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJlbl = new javax.swing.JLabel();
        yourRequestedStudiesJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studyRequestsJTable = new javax.swing.JTable();
        requestNewStudyJBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        assignPatientsJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerJlbl.setFont(new java.awt.Font("Levenim MT", 1, 24)); // NOI18N
        headerJlbl.setForeground(new java.awt.Color(0, 204, 204));
        headerJlbl.setText("Request Study Panel");
        add(headerJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 25, 260, -1));

        yourRequestedStudiesJLabel.setFont(new java.awt.Font("Levenim MT", 1, 18)); // NOI18N
        yourRequestedStudiesJLabel.setForeground(new java.awt.Color(0, 204, 204));
        yourRequestedStudiesJLabel.setText("Your Requested Studies");
        add(yourRequestedStudiesJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 93, -1, -1));

        studyRequestsJTable.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        studyRequestsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Study Name", "Study Message", "Scientist", "Study Status", "Drug", "Recruitment Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studyRequestsJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 137, 802, 160));

        requestNewStudyJBtn.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        requestNewStudyJBtn.setText("Request A New Study");
        requestNewStudyJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestNewStudyJBtnActionPerformed(evt);
            }
        });
        add(requestNewStudyJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 332, -1, -1));

        backBtn.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 332, -1, -1));

        assignPatientsJBtn.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        assignPatientsJBtn.setText("Assign Patients");
        assignPatientsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignPatientsJBtnActionPerformed(evt);
            }
        });
        add(assignPatientsJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 332, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestNewStudyJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestNewStudyJBtnActionPerformed
        // TODO add your handling code here: RequestNewStudyJPanel
        RequestNewStudyJPanel rnsjp = new RequestNewStudyJPanel(userProcessContainer, business, userAccount, doctorOrganization, enterprise,inNetwork);
        userProcessContainer.add("RequestNewStudyJPanel", rnsjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestNewStudyJBtnActionPerformed

    private void assignPatientsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignPatientsJBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = studyRequestsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row!");
            return;
        } else if (((StudyWorkRequest) studyRequestsJTable.getValueAt(selectedRow, 1)).getStudy().getRecruitmentStatus().equals("New")) {
            JOptionPane.showMessageDialog(this, "Patient not yet requested!!");
            return;
        } else if (((StudyWorkRequest) studyRequestsJTable.getValueAt(selectedRow, 1)).getStudy().getRecruitmentStatus().equals("Patients Assigned")) {
            JOptionPane.showMessageDialog(this, "Patient already Assigned!!");
            return;
        } else {
            StudyWorkRequest req = (StudyWorkRequest) studyRequestsJTable.getValueAt(selectedRow, 1);
            int requiredCount = req.getStudy().getRecruitmentNumber();
            int currentCount = 0;
            for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (o instanceof PatientOrganization) {
                    for (Patient p : o.getPatientDirectory().getPatientDirectory()) {
                        currentCount++;
                        if (currentCount<=requiredCount) {
                            req.getStudy().addPatient(p); // Adding required number of patients to the study patient list
                        }
                        else{
                            break;
                        }
                    }
                    req.getStudy().setRecruitmentStatus("Patients Assigned");
                }
            }
            JOptionPane.showMessageDialog(this, "Patient assigned successfully!");
            populateTable();
        }
    }//GEN-LAST:event_assignPatientsJBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignPatientsJBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel headerJlbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton requestNewStudyJBtn;
    private javax.swing.JTable studyRequestsJTable;
    private javax.swing.JLabel yourRequestedStudiesJLabel;
    // End of variables declaration//GEN-END:variables
}