/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.doctorWorkArea;

import business.Ecosystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.userAcoount.UserAccount;
import javax.swing.JPanel;
import business.organization.DoctorOrganization;
import business.organization.Organization;
import business.organization.PatientOrganization;
import business.organization.ScientistOrganization;
import business.workqueue.ScheduleAppointmentWorkRequest;
import business.workqueue.StudyWorkRequest;
import business.workqueue.WorkRequest;

import java.awt.BorderLayout;
import java.awt.CardLayout;

import java.awt.Color;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Harsh
 */
public class ShowReportsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Ecosystem business;
    private UserAccount userAccount;
    private DoctorOrganization doctorOrganization;
    private Enterprise enterprise;

    public ShowReportsJPanel(JPanel userProcessContainer, Ecosystem business, UserAccount userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.doctorOrganization = (DoctorOrganization) organization;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJLabel = new javax.swing.JLabel();
        showJButton = new javax.swing.JButton();
        panelChart = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectionJComboBox = new javax.swing.JComboBox<>();
        backJbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerJLabel.setFont(new java.awt.Font("Levenim MT", 1, 24)); // NOI18N
        headerJLabel.setForeground(new java.awt.Color(0, 204, 204));
        headerJLabel.setText("      Show Reports");
        add(headerJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 10, 255, -1));

        showJButton.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        showJButton.setForeground(new java.awt.Color(0, 204, 204));
        showJButton.setText("Show");
        showJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showJButtonActionPerformed(evt);
            }
        });
        add(showJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 55, 126, -1));

        panelChart.add(jScrollPane2);

        add(panelChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 650, 425));

        selectionJComboBox.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        selectionJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Number Of patients Treated", "Number of Studies requested" }));
        add(selectionJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 56, -1, -1));

        backJbtn.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        backJbtn.setForeground(new java.awt.Color(0, 204, 204));
        backJbtn.setText("<<Back");
        backJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbtnActionPerformed(evt);
            }
        });
        add(backJbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 55, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void showJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showJButtonActionPerformed
        // TODO add your handling code here:

        
        String selection = selectionJComboBox.getSelectedItem().toString();
        
        if (selection.equalsIgnoreCase("Number Of patients Treated")) {
            DefaultCategoryDataset barChartData = new DefaultCategoryDataset();
            int count = 0;
            

            for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (o instanceof DoctorOrganization) {
                    for (WorkRequest req : o.getWorkQueue().getWorkRequestList()) {
                        System.out.println("ua :"+userAccount.getUsername());
                        System.out.println("req :"+req.getReceiver());
                        if (req.getStatus().equals("Treatment Complete") && req.getReceiver().equals(userAccount)) {

                            count++;
                        }
                    }
                }
            }

            
            
            barChartData.setValue(count, "Patients", "1");
            
            JFreeChart barChart = ChartFactory.createBarChart("Patients", "year", "Number Of Patients", barChartData, PlotOrientation.VERTICAL, false, true, false);
            
            CategoryPlot barChrt = barChart.getCategoryPlot();
            barChrt.setRangeGridlinePaint(Color.ORANGE);

            

            ChartPanel barPanel = new ChartPanel(barChart);
            barPanel.setSize(350, 500);
            panelChart.removeAll();
            panelChart.add(barPanel, BorderLayout.CENTER);
            panelChart.repaint();
            panelChart.validate();
        } else if (selection.equalsIgnoreCase("Number of Studies requested")) {

            DefaultCategoryDataset barChartData = new DefaultCategoryDataset();
            int count = 0;
            
            for (Network n : business.getNetworkList()) {
                for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                    
                    for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                        
                        if (o instanceof ScientistOrganization) {

                            for (WorkRequest req : o.getWorkQueue().getWorkRequestList()) {
                                
                                if (req instanceof StudyWorkRequest && req.getSender().equals(userAccount)) {

                                    
                                    count++;
                                }
                            }
                        }
                    }
                }
            }

            
            barChartData.setValue(count, "Studies", "1");
            
            JFreeChart barChart = ChartFactory.createBarChart("Studies", "year", "Number Of Studies", barChartData, PlotOrientation.VERTICAL, false, true, false);
            
            CategoryPlot barChrt = barChart.getCategoryPlot();
            barChrt.setRangeGridlinePaint(Color.ORANGE);

            ChartPanel barPanel = new ChartPanel(barChart);
            barPanel.setSize(350, 500);
            panelChart.removeAll();
            panelChart.add(barPanel, BorderLayout.CENTER);
            panelChart.repaint();
            panelChart.validate();
        }


    }//GEN-LAST:event_showJButtonActionPerformed

    private void backJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);


    }//GEN-LAST:event_backJbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJbtn;
    private javax.swing.JLabel headerJLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelChart;
    private javax.swing.JComboBox<String> selectionJComboBox;
    private javax.swing.JButton showJButton;
    // End of variables declaration//GEN-END:variables
}
